### ISSUE TITLE
Add a second DoubleSolenoid

### ISSUE THREAD

**Issue by willitcode** [frc937/pneumatics-test#1]
Pneumatics peeps may need a second double solenoid added real quick on the 27th—it depends on if they get it installed in the system or not. @QuackitsQuinn, you should be able to figure out how to do this relatively easily. Ask them if they want separate buttons to extend/retract each or if they want one button that extends/retracts both at the same time (as will be on the actual robot).

**Comment by willitcode** [comment]
Can also be a problem for Ara/Jack to solve. It just needs to get done *quickly*, since the pneumatics folks will probably get it done and want the code right away. (or you can just start working on it before they're done, but you likely won't have solenoid ids yet). I also don't want Jack to get confused by bouncing back and forth between command-based and timed robots.

**Comment by AraReighard** [comment]
Mechanical peeps don't need a second solenoid. They will simply plug the piston into the 1st solenoid.

**Comment by AraReighard** [comment]
Mechanical peeps need a second solenoid. Whoops!
